config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/dashboard", to: "pages#dashboard", as: :dashboard
  resources :patients, only: [:show, :new, :create, :update, :edit, :index] do
    resources :medical_records, only: [:index, :new, :create, :edit, :update, :destroy, :show, :search]
    get "/scan", to: "medical_records#scan", as: :scan
    member do
      patch "autofill"
    end
  end
  resources :medical_records, only: [:update]
  resources :doctors, only: [:show, :new, :create, :update, :edit]
  namespace :doctor do
    resources :medical_records, only: [:index, :new, :create, :edit, :update, :destroy, :show]
  end
  resources :events, only: [:index, :show, :new, :create, :update, :edit, :destroy]
  get "calendar", to: "pages#calendar", as: "calendar"
  get "/map", to: "pages#map", as: "map"

  resources :conditions, only: [:show, :new, :create]
  namespace :general do
    resources :conditions, only: [:index]
  end
end

app/models/medical_record.rb
class MedicalRecord < ApplicationRecord
  belongs_to :patient
  belongs_to :doctor, optional: true, default: false
  has_many_attached :photos
  belongs_to :condition, optional: true
  has_one_attached :photo_form
  enum creator: { patient: 0, doctor: 1 }
  enum type: { chronic_illnesses: 0, surgeries: 1, physical_injuries: 2 }

  SYMPTOMS = [
    "I have fever",
    "I have a stomach ache",
    "I am sick",
    "I have a diarrhea",
    "I am vomiting",
    "I have a runny nose",
    "I have a cough",
    "I have a pharynx pain",
    "I have a headache",
    "Others. Please describe."
  ]
end

app/controllers/doctor/medical_records_controller.rb
class Doctor::MedicalRecordsController < ApplicationController
  def index
    # @medical_records = MedicalRecord.where(MedicalRecord.doctor == current_user.doctor)
    @medical_records = policy_scope([:doctor, MedicalRecord]).order(date: :desc)
  end
end

app/controllers/medical_records_controller.rb
require "rqrcode"

class MedicalRecordsController < ApplicationController
  def index
    @patient = current_user.doctor? ? Patient.find(params[:patient_id]) : current_user.patient.id
    @medical_records = policy_scope(MedicalRecord.where(patient: @patient)).order(date: :desc)
    @conditions = Condition.where(patient: @patient)
  end

  def new
    @patient = current_user.doctor? ? Patient.find(params[:patient_id]) : current_user.patient.id
    @medical_record = MedicalRecord.new
    @conditions = Condition.where(patient: @patient)
    @medical_record.patient = Patient.find(params[:patient_id])
    authorize @medical_record
  end

  def show
    @medical_record = MedicalRecord.find(params[:id])
    authorize @medical_record
    if @medical_record.photo_form.attached?
      if Rails.env == "development"
        image = "https://res.cloudinary.com/dystex7k9/image/upload/v1654167978/development/#{@medical_record.photo_form.key}"#helpers.url_for(@cosmetic.cosmetic_image)
        # image = "https://res.cloudinary.com/dystex7k9/image/upload/v1654167978/development/#{@medical_record.photo_form.key}"#helpers.url_for(@cosmetic.cosmetic_image)

      else
        image = "https://res.cloudinary.com/dystex7k9/image/upload/v1654167978/production/#{@medical_record.photo_form.key}"#helpers.url_for(@cosmetic.cosmetic_image)
        # image = "https://res.cloudinary.com/dystex7k9/image/upload/v1654167978/production/#{@medical_record.photo_form.key}"#helpers.url_for(@cosmetic.cosmetic_image)
      end
      @infos = Ocr.locate_text(image, @medical_record)
    end
  end

  def create
    @medical_record = MedicalRecord.new(record_params)
    @patient = Patient.find(params[:patient_id])
    @medical_record.patient = @patient
    @medical_record.creator = current_user.user_type
    @medical_record.date = Date.today
    @medical_record.doctor = current_user.doctor? ? current_user.doctor : nil
    # params[:medical_record][:symptoms].each do |symptom|
    #   @medical_record.symptoms.push(symptom) if symptom != ""
    # end

    authorize @medical_record

    if @medical_record.save
      redirect_to patient_medical_record_path(@medical_record.patient, @medical_record), notice: 'Record was saved.'
    else
      render :new, notice: 'Record was not saved. Please try again.'
    end
  end

  def edit
    @medical_record = MedicalRecord.find(params[:id])
    authorize @medical_record
  end

  def update
    # raise StandardError, 'NotAuthorized' unless @restaurant.user == current_user
    @medical_record = MedicalRecord.find(params[:id])
    authorize @medical_record
    if @medical_record.update(record_params)
      redirect_to patient_medical_record_path(@medical_record.patient, @medical_record), notice: 'Record was successfully updated.'
    else
      render :edit
    end
  end

  def autofill
    @medical_record = MedicalRecord.new(record_params)
    @medical_record.patient = Patient.find(params[:patient_id])
    @medical_record.creator = current_user.user_type
    @medical_record.date = Date.today
    @medical_record.doctor = current_user.doctor? ? current_user.doctor : nil
    params[:medical_record][:symptoms].each do |symptom|
      @medical_record.symptoms.push(symptom) if symptom != ""
    end

    authorize @medical_record
    @patient = Patient.find(params[:id])
    authorize @patient
    @patient.update(patient_params)
    if Rails.env == "development"
      image = "https://res.cloudinary.com/dystex7k9/image/upload/v1654167978/development/#{@patient.id_card.key}"#helpers.url_for(@cosmetic.cosmetic_image)
    else
      image = "https://res.cloudinary.com/dystex7k9/image/upload/v1654167978/production/#{@patient.id_card.key}"
    end
    @infos = Ocr.locate_text(image, @patient)
    render "medical_records/ocr_form.html"
  end

  def destroy
    @medical_record = MedicalRecord.find(params[:id])
    authorize @medical_record
    @medical_record.destroy
    redirect_to "medical_records/index", notice: "Are you sure you'd like to delete this record? If deleted, it cannot be restored"
  end

  def scan
    @medical_record = MedicalRecord.new
    @medical_record.patient = Patient.find(params[:patient_id])
    authorize @medical_record
  end

  private

  def record_params
    params.require(:medical_record).permit(:patient_id, :doctor_id, :photo_form, :doctor_name, :problem_since, :diagnosis, :creator, :date, :condition_id, :prescribed_medicine, photos: [], symptoms: [])
  end
end

app/views/medical_records/_condition.html.erb
<%= link_to condition_path(condition), style:"text-decoration:none;" do  %>
  <div class="item-drawer-condition">
    <%= condition.name %>
  </div>
<% end %>

app/views/medical_records/_medical_record.html.erb
<div data-controller="drawer" data-drawer-target="drawer" class="item-drawer">
  <div class="item-drawer-content">
    <h5><%= medical_record.date %></h5>
    <p><%= medical_record.doctor_name %></p>
    <% if medical_record.symptoms[0] == "" %>
      <li><%= medical_record.symptoms[1] %></li>
    <% elsif medical_record.symptoms? %>
      <%= medical_record.symptoms[0] %>
    <% end %>
  </div>
  <div  data-action="click->drawer#open"  class="item-drawer-button">
    <i class="fas fa-ellipsis-v fa-1x"></i>
  </div>
  <div class="item-drawer-settings">
    <a href="<%= patient_medical_record_path(medical_record.patient, medical_record) %>"><i class="fas fa-folder-open fa-1x"></i></a>
    <a href="<%= edit_patient_medical_record_path(medical_record.patient, medical_record) %>"><i class="fas fa-pencil-alt fa-1x"></i></a>
  </div>
</div>

app/views/medical_records/edit.html.erb
<div class="container mt-3">
  <h1>Edit Medical Record</h1>
  <div class="container mb-5 pb-5">
    <%= simple_form_for [@medical_record.patient, @medical_record] do |f| %>
      <%= f.input :date, start_year: Time.now.year - 100 %>
      <%= f.input :symptoms, as: :check_boxes, collection: MedicalRecord::SYMPTOMS, input_html: { multiple: true }, wrapper: :vertical_collection_inline %>
      <% if :symptoms == "others" %>
        <%= f.input :symptoms, as: :text %>
      <% end %>
      <%= f.input :diagnosis %>
      <%= f.input :prescribed_medicine %>
      <% if current_user.user_type == "patient" %>
        <%= f.input :doctor_name %>
      <% end %>
      <%= f.input :photos, as: :file, input_html: { multiple: true }  %>
      <%= f.button :submit, "Update", class: "btn btn-primary mt-3" %>
    <% end %>
  </div>
</div>

app/views/medical_records/index.html.erb
<div class="container mt-3 mb-5 pb-5">
  <% if current_user.doctor? %>
    <h1><%= image_tag (@patient.photo.attached? ? cl_image_path(@patient.photo.key) : "user.png"), class: "avatar" %><%= @patient.first_name%>'s Medical History</h1>
  <% else %>
    <h1>Medical History</h1>
  <% end %>

  <br>
  <%= link_to general_conditions_path, style:"text-decoration:none;" do  %>
    <div class="item-drawer-condition">
      <%= "General" %>
    </div>
  <% end %>
  <% @conditions.each do |condition| %>
    <%= render "condition", condition: condition  %>
  <% end %>
</div>
<div class="container">
  <%= link_to "Create New Condition", new_condition_path, class:"btn btn-primary mt-3 mb-3", style:"position: absolute; left: 12px; bottom: 130px;" %>
</div>

app/views/medical_records/new.html.erb
<div class="container mt-3">
  <div class="container mb-5 pb-5">
    <div class="row justify-content-center">
      <div class="col col-sm-8 col-md-6" data-controller="loading-screen">
        <h1 class='text-start' data-loading-screen-target='header'>Medical History Form</h1>
        <%= simple_form_for [@medical_record.patient, @medical_record], html: { data: { loading_screen_target: 'form' } } do |f| %>
          <%= f.association :condition, as: :select, collection: @conditions%>
          <%= f.input :photo_form, input_html: { class: 'd-none', data: { action: 'change->loading-screen#startLoad' } }, label_html: { class: 'upload-photo'}, label: '📷 Upload a form', onchange: 'this.form.submit()'  %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/medical_records/scan.html.erb
<div class="container mt-3">
  <h1>Medical History Form</h1>
  <div class="container mb-5 pb-5">
    <%= simple_form_for [@medical_record.patient, @medical_record] do |f| %>
      <%= f.association :condition %>
      <%= f.input :photo_form, as: :file %> <!-- You can style / change to camera later -->
      <%= f.submit 'Upload', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/medical_records/show.html.erb
<div class="container mb-5 pb-5">
  <div class="card-category-profile no-print">
    <div class="d-flex justify-content-between w-100">
      <i class="fas fa-signature"></i>
      <p class="w-75"><%= "#{@medical_record.patient.first_name} #{@medical_record.patient.last_name}" %></p>
    </div>
    <div class="d-flex justify-content-between w-100">
      <i class="far fa-calendar-alt"></i>
      <p class="w-75"><%= "#{@medical_record.patient.date_of_birth}" %></p>
    </div>
    <div class="d-flex justify-content-between w-100">
      <i class="fas fa-venus-mars"></i>
      <p class="w-75"><%= "#{@medical_record.patient.sex}" %></p>
    </div>
    <div class="d-flex justify-content-between w-100">
      <i class="fas fa-ruler"></i>
      <p class="w-75"><%= "#{@medical_record.patient.height}" %> cm</p>
    </div>
    <div class="d-flex justify-content-between w-100">
      <i class="fas fa-weight"></i>
      <p class="w-75"><%= "#{@medical_record.patient.weight}" %> kg</p>
    </div>
    <div class="d-flex justify-content-between w-100">
      <i class="fas fa-plane"></i>
      <p class="w-75">Traveled recently: <%= @medical_record.patient.traveled_from_abroad? ? "Yes" : "No" %></p>
    </div>
    <div class="d-flex justify-content-between w-100">
      <% if @medical_record.patient.smoker? %>
        <i class="fas fa-smoking"></i>
      <% end %>
    </div>
    <div class="d-flex justify-content-between w-100">
      <i class="fas fa-tint"></i>
      <p class="w-75">Blood type: <%= "#{@medical_record.patient.blood_type}" %></p>
    </div>
    <div class="d-flex justify-content-between w-100">
      <i class="fas fa-allergies"></i>
      <p class="w-75">Allergies: <%= "#{@medical_record.patient.allergies}" %></p>
    </div>
    <div class="d-flex justify-content-between w-100">
      <% if @medical_record.patient.female? %>
        <i class="fas fa-baby"></i>
        <p class="w-75"><%= @medical_record.patient.pregnancy? ? "Yes" : "No" %></p>
        <i class="fas fa-jug"></i>
        <p class="w-75"><%= @medical_record.patient.lactation? ? "Yes" : "No" %></p>
      <% end %>
    </div>
    <div class="d-flex justify-content-between w-100">
      <i class="fas fa-heartbeat"></i>
      <p class="w-75">Health problems: <%= "#{@medical_record.patient.health_problems}" %></p>
    </div>
    <div class="d-flex justify-content-between w-100">
      <i class="fas fa-medkit"></i>
      <p class="w-75">Family history: <%= "#{@medical_record.patient.family_health_problems}" %></p>
    </div>
    <div class="d-flex justify-content-between w-100">
      <i class="fas fa-capsules"></i>
      <p class="w-75">Medications: <%= "#{@medical_record.patient.usual_medication}" %></p>
    </div>
    <h2><strong>Visit Info:</strong></h2>
    <h5><strong>Symptoms:</strong> </h5>
    <ul>
      <% @medical_record.symptoms.each do |symptom| %>
        <li><%= "#{symptom}" %></li>
      <% end %>
    </ul>
    <% if @medical_record.problem_since? %>
      <h5><strong>Since:</strong> <%= "#{@medical_record.problem_since}" %></h5>
    <% end %>
    <% if @medical_record.diagnosis? %>
      <h5 class="mark"><strong>Diagnosis:</strong> <%= "#{@medical_record.diagnosis}" %></h5>
    <% end %>
    <% if @medical_record.prescribed_medicine? %>
      <h5><strong>Prescribed Medicine:</strong> <%= "#{@medical_record.prescribed_medicine}" %></h5>
    <% end %>
    <div data-controller="lightbox">
      <% @medical_record.photos.each do |photo| %>
        <%= cl_image_tag photo.key, crop: :fill, class:'zoomD unzoom' %>
      <% end %>
    </div>
    <% if @medical_record.doctor_id? %>
      <h5>Doctor name: </h5>
      <p><%= "#{@medical_record.doctor.first_name}" %></p>
    <% elsif @medical_record.doctor_name? %>
      <h5>Doctor name: </h5>
      <p><%= "#{@medical_record.doctor_name}" %></p>
    <% end %>
    <% if current_user.doctor? %>
      <a href="<%= edit_patient_medical_record_path(@medical_record.patient, @medical_record) %>"><i class="fas fa-pencil-alt fa-1x"></i></a>
    <% end %>
  </div>
  <% if @medical_record.photo_form.attached?%>
    <div class="to-print">
      <button onclick="window.print();" class="no-print btn btn-primary mb-3">PRINT</button>
      <div data-controller="resize" class="resize-wrapper">
        <div data-resize-target="toResize" class="resize-element">
          <div class="position-relative">
            <%= simple_form_for @medical_record do |f| %>
              <% @infos.each do |info| %>
                <div class="position-absolute display-4 text-weight-bold <%= info[:class] %>" style="top: <%= info[:location].last %>px; left: <%= info[:location].first%>px;<%= info[:style] %>">
                  <span><%= info[:text] %></span>
                </div>
              <% end %>
            <% end %>
          </div>
          <%= cl_image_tag(@medical_record.photo_form.key, height: 4032, width: 3024) %>
        </div>
        <%= cl_image_tag(@medical_record.photo_form.key) %>
      </div>
    </div>
  <% end %>
</div>