config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/dashboard", to: "pages#dashboard", as: :dashboard
  resources :patients, only: [:show, :new, :create, :update, :edit, :index] do
    resources :medical_records, only: [:index, :new, :create, :edit, :update, :destroy, :show, :search]
    get "/scan", to: "medical_records#scan", as: :scan
    member do
      patch "autofill"
    end
  end
  resources :medical_records, only: [:update]
  resources :doctors, only: [:show, :new, :create, :update, :edit]
  namespace :doctor do
    resources :medical_records, only: [:index, :new, :create, :edit, :update, :destroy, :show]
  end
  resources :events, only: [:index, :show, :new, :create, :update, :edit, :destroy]
  get "calendar", to: "pages#calendar", as: "calendar"
  get "/map", to: "pages#map", as: "map"

  resources :conditions, only: [:show, :new, :create]
  namespace :general do
    resources :conditions, only: [:index]
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <% if user_signed_in? && current_user.user_type == "patient" %>
    <div class="container-fluid d-flex justify-content-around icon-container">
      <%= link_to :back do %>
        <i class="fas fa-undo fa-2x icon-cog pt-2"></i>
      <% end %>
      <%= link_to edit_user_registration_path(current_user) do %>
        <i class="fas fa-unlock-alt fa-2x icon-cog pt-2"></i>
      <% end %>
      <div class="w-10">
        <div class="circle">
          <div class="btn btn-flat" data-bs-toggle="modal" data-bs-target="#exampleModal">
            <i class="fas fa-qrcode fa-3x icon-cog"></i>
          </div>
        </div>
      </div>
      <%= link_to patient_path(current_user.patient) do %>
        <i class="fas fa-user fa-2x icon-cog pt-2"></i>
      <% end %>
      <%= link_to dashboard_path do %>
        <i class="fas fa-home fa-2x icon-cog pt-2"></i>
      <% end %>
    </div>
  <% elsif user_signed_in? && current_user.doctor? %>
    <div class="container-fluid d-flex justify-content-around icon-container">
      <%= link_to :back do %>
        <i class="fas fa-undo fa-2x icon-cog pt-2"></i>
      <% end %>
      <%= link_to edit_user_registration_path(current_user) do %>
        <i class="fas fa-unlock-alt fa-2x icon-cog pt-2"></i>
      <% end %>
      <%= link_to doctor_path(current_user.doctor) do %>
        <i class="fas fa-user-md fa-2x icon-cog pt-2"></i>
      <% end %>
      <%= link_to dashboard_path do %>
        <i class="fas fa-home fa-2x icon-cog pt-2"></i>
      <% end %>
    </div>
  <% else %>
    <div class="container-fluid d-flex justify-content-around py-1 ">
    </div>
  <% end %>
</div>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_modal.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <% if current_user.user_type == 'patient' %>
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Scan For Medical Records</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <div class="qr-code mt-3 d-flex justify-content-center">
            <%= current_user.patient.qr_code("https://www.medrec-858.me/#{patient_medical_records_path(current_user.patient.id)}").html_safe %>
          </div>
        </div>
        <div class="modal-footer">
          <button class="btn btn-primary" data-bs-target="#exampleModalToggle2" data-bs-toggle="modal" data-bs-dismiss="modal">Give Access</button>
        </div>
      <%end%>
    </div>
  </div>
</div>
<div class="modal fade" id="exampleModalToggle2" aria-hidden="true" aria-labelledby="exampleModalToggleLabel2" tabindex="-1">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalToggleLabel2">Password:</h5>
      </div>
      <div class="modal-body">
        <h3>73s7d5xc3</h3>
      </div>
      <div class="modal-footer">
        <button class="btn btn-primary" data-bs-target="#exampleModalToggle" data-bs-toggle="modal" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to dashboard_path, class: "navbar-brand" do %>
      <%= image_tag("newlogo4.png", alt: "logo") %>
    <% end %>
    <% if user_signed_in? && current_user.patient? %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <%= image_tag (current_user.patient.photo.attached? ? cl_image_path(current_user.patient.photo.key) : "user.png"), class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <li class="nav-item active" style="text-align: end">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item text-black" %>
          </li>
        </ul>
      <% elsif user_signed_in? && current_user.doctor? %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <%= image_tag (current_user.doctor.photo.attached? ? cl_image_path(current_user.doctor.photo.key) : "user.png"), class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto">
            <li class="nav-item active"  style="text-align: end">
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item text-black" %>
            </li>
          </ul>
        <% else %>
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        <% end %>
      </div>
    </div>
  </div>
</div>