config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/dashboard", to: "pages#dashboard", as: :dashboard
  resources :patients, only: [:show, :new, :create, :update, :edit, :index] do
    resources :medical_records, only: [:index, :new, :create, :edit, :update, :destroy, :show, :search]
    get "/scan", to: "medical_records#scan", as: :scan
    member do
      patch "autofill"
    end
  end
  resources :medical_records, only: [:update]
  resources :doctors, only: [:show, :new, :create, :update, :edit]
  namespace :doctor do
    resources :medical_records, only: [:index, :new, :create, :edit, :update, :destroy, :show]
  end
  resources :events, only: [:index, :show, :new, :create, :update, :edit, :destroy]
  get "calendar", to: "pages#calendar", as: "calendar"
  get "/map", to: "pages#map", as: "map"

  resources :conditions, only: [:show, :new, :create]
  namespace :general do
    resources :conditions, only: [:index]
  end
end

app/views/pages/calendar.html.erb
<div class="container mt-3 mb-5 pb-5" data-controller="flatpickr">
  <%= month_calendar(events: @events) do |date, events| %>
    <%= date.day %>
    <% events.each do |event| %>
      <p class="event"><%= event.title.capitalize %></p>
    <% end %>
  <% end %>
</div>

app/views/pages/dashboard.html.erb
<div class="container mt-3 mb-3" style="height: 55vh; align-items: center; display: flex;">
  <% if user_signed_in? && current_user.user_type == "patient" %>
    <div class="cards container">
      <div class="row justify-content-center row-cols-2">
        <div class="col">
          <%= link_to patient_medical_records_path(current_user.patient) do%>
            <div class="card-category-dashboard">
              <i class="fas fa-file-medical fa-3x"></i>
              <p>Records</p>
            </div>
          <% end %>
        </div>
        <div class="col">
          <%= link_to calendar_path do%>
            <div class="card-category-dashboard">
              <i class="far fa-calendar-alt fa-3x"></i>
              <p>Calendar</p>
            </div>
          <% end %>
        </div>
      </div>
      <div class="row justify-content-center row-cols-2">
        <div class="col">
          <%= link_to map_path do%>
            <div class="card-category-dashboard">
              <i class="fas fa-map-marker-alt fa-3x"></i>
              <p>Map</p>
            </div>
          <% end %>
        </div>
        <div class="col">
          <%= link_to new_patient_medical_record_path(current_user.patient) do %>
            <div class="card-category-dashboard">
              <i class="fas fa-paste fa-3x"></i>
              <p>New Form</p>
            </div>
          <% end %>
        </div>
      </div>
    <% elsif user_signed_in? && current_user.user_type == "doctor" %>
      <div class="cards container">
        <div class="row justify-content-center row-cols-2">
          <div class="col">
            <%= link_to patients_path do%>
              <div class="card-category-dashboard first">
                <i class="fa fa-book fa-3x" aria-hidden="true"></i>
                <p>Patients</p>
              </div>
            <% end %>
          </div>
          <div class="col">
            <%= link_to doctor_medical_records_path do%>
              <div class="card-category-dashboard">
                <i class="fas fa-file-medical fa-3x"></i>
                <p>Medical Records</p>
              </div>
            <% end %>
          </div>
        </div>
        <div class="row justify-content-center row-cols-2">
          <div class="col">
            <%= link_to dashboard_path do%>
              <div class="card-category-dashboard">
                <i class="fas fa-qrcode fa-3x" aria-hidden="true"></i>
                <p>Scan</p>
              </div>
            <% end %>
          </div>
          <div class="col">
            <%= link_to map_path do%>
              <div class="card-category-dashboard">
                <i class="fas fa-map-marker-alt fa-3x"></i>
                <p>Map</p>
              </div>
            <% end %>
          </div>
        </div>
      <% else %>
        <div class="cards container">
          <%= link_to map_path do%>
            <div class="card-category-dashboard">
              <i class="fas fa-map-marker-alt fa-3x"></i>
              <p>Map</p>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>

app/views/pages/home.html.erb
<div class="background" style="padding: 0; background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)) url(images/newbackground3.jpg);">
  <div class="mask" style="background-color: rgba(0, 0, 0, 0.3); height: 100vh;">
    <div class="container mb-3 d-flex-column">
      <%= image_tag("newlogo4.png", alt: "logo", style: 'width:100%;', class:'mt-1') %>
      <h1 class="mt-3 text-white"><strong>Take Your Health With You</strong></h1>
      <%= link_to dashboard_path, class:"btn-gradient" do%>
        <i class="fas fa-chevron-right mt-3 text-white"></i>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/map.html.erb
<div class="container mt-3">
  <div style="width: 100%; height: 600px;"
    data-controller="mapbox"
    data-mapbox-markers-value="<%= @markers.to_json %>"
    data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>